[package]
name = "DalamudRepoTool"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.13"
serde_json = "1.0.117"
chrono = { version = "^0.4.1", features = ["serde", "rustc-serialize"] }
clap = { version = "4.5", features = ["derive"] }